spring:
 datasource:
   url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sacola-api-db
   username: postgres
   password: 1234
   driverClassName: org.postgresql.Driver
 jpa:
   show-sql: true
   defer-datasource-initialization: true 
   database-platform: org.hibernate.dialect.PostgreSQLDialect